/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
"use strict";

systemDictionary = {
    "pylontech adapter settings": {
        en: "Adapter settings for pylontech",
        de: "Adaptereinstellungen für pylontech",
        ru: "Настройки адаптера для pylontech",
        pt: "Configurações do adaptador para pylontech",
        nl: "Adapterinstellingen voor pylontech",
        fr: "Paramètres d'adaptateur pour pylontech",
        it: "Impostazioni dell'adattatore per pylontech",
        es: "Ajustes del adaptador para pylontech",
        pl: "Ustawienia adaptera dla pylontech",
        "zh-cn": "pylontech的适配器设置",
    },
    device: {
        en: "Device oder Port",
        de: "Device oder Port",
        ru: "Device oder Port",
        pt: "Device oder Port",
        nl: "Device oder Port",
        fr: "Device oder Port",
        it: "Device oder Port",
        es: "Device oder Port",
        pl: "Device oder Port",
        "zh-cn": "Device oder Port",
    },
    password: {
        en: "password",
        de: "password",
        ru: "password",
        pt: "password",
        nl: "password",
        fr: "password",
        it: "password",
        es: "password",
        pl: "password",
        "zh-cn": "password",
    },
    log: {
        en: "Log",
        de: "Log",
        ru: "Log",
        pt: "Log",
        nl: "Log",
        fr: "Log",
        it: "Log",
        es: "Log",
        pl: "Log",
        "zh-cn": "Log",
    },
    batterycells: {
        en: "Battery cells",
        de: "Battery cells",
        ru: "Battery cells",
        pt: "Battery cells",
        nl: "Battery cells",
        fr: "Battery cells",
        it: "Battery cells",
        es: "Battery cells",
        pl: "Battery cells",
        "zh-cn": "Battery cells",
    },
    statistics: {
        en: "Statistics",
        de: "Statistics",
        ru: "Statistics",
        pt: "Statistics",
        nl: "Statistics",
        fr: "Statistics",
        it: "Statistics",
        es: "Statistics",
        pl: "Statistics",
        "zh-cn": "Statistics",
    },
    accuinformation: {
        en: "Accu information",
        de: "Accu information",
        ru: "Accu information",
        pt: "Accu information",
        nl: "Accu information",
        fr: "Accu information",
        it: "Accu information",
        es: "Accu information",
        pl: "Accu information",
        "zh-cn": "Accu information",
    },
    cycle: {
        en: "Cycle time in minutes",
        de: "Cycle time in minutes",
        ru: "Cycle time in minutes",
        pt: "Cycle time in minutes",
        nl: "Cycle time in minutes",
        fr: "Cycle time in minutes",
        it: "Cycle time in minutes",
        es: "Cycle time in minutes",
        pl: "Cycle time in minutes",
        "zh-cn": "Cycle time in minutes",
    },
};
