/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
'use strict';

systemDictionary = {
  'pylontech adapter settings': {
    en: 'Adapter settings for pylontech',
    de: 'Adaptereinstellungen für pylontech',
    ru: 'Настройки адаптера для pylontech',
    pt: 'Configurações do adaptador para pylontech',
    nl: 'Adapterinstellingen voor pylontech',
    fr: "Paramètres d'adaptateur pour pylontech",
    it: "Impostazioni dell'adattatore per pylontech",
    es: 'Ajustes del adaptador para pylontech',
    pl: 'Ustawienia adaptera dla pylontech',
    'zh-cn': 'pylontech的适配器设置',
  },
  'Local device': {
    en: 'Local device',
    de: 'Lokales Gerät',
    ru: 'Местное устройство',
    pt: 'Dispositivo local',
    nl: 'Lokaal',
    fr: 'Appareil local',
    it: 'Dispositivo locale',
    es: 'Dispositivo local',
    pl: 'Miejsca lokalna',
    uk: 'Місцевий пристрій',
    'zh-cn': '当地装置',
  },
  'network device': {
    en: 'Network device',
    de: 'Netzwerkgerät',
    ru: 'Сетевой прибор',
    pt: 'Dispositivo de rede',
    nl: 'Netwerk',
    fr: 'Appareil réseau',
    it: 'Dispositivo di rete',
    es: 'Dispositivo de red',
    pl: 'Urządzenia Network',
    uk: 'Мережевий пристрій',
    'zh-cn': '网络装置',
  },
  'Connection via': {
    en: 'Connection via',
    de: 'Verbindung über',
    ru: 'Подключение через',
    pt: 'Conexão via',
    nl: 'Verbinding via',
    fr: 'Connexion via',
    it: 'Connessione tramite',
    es: 'Conexión mediante',
    pl: 'Połączenie poprzez',
    uk: 'Підключення через',
    'zh-cn': '通过控制',
  },
  'Local device path': {
    en: 'Local device path\n',
    de: 'Lokaler Gerätepfad\n',
    ru: 'Местный путь устройства\n',
    pt: 'Caminho do dispositivo local\n',
    nl: 'Lokale pad\n',
    fr: 'Local device path\n',
    it: 'Percorso del dispositivo locale\n',
    es: 'Camino del dispositivo local\n',
    pl: 'Ścieżka lokalna\n',
    uk: 'Шлях місцевого пристрою\n',
    'zh-cn': '当地装置\n',
  },
  'Transmission speed': {
    en: 'Transmission speed',
    de: 'Übertragungsgeschwindigkeit',
    ru: 'Скорость передачи',
    pt: 'Velocidade de transmissão',
    nl: 'Transmissie snelheid',
    fr: 'Vitesse de transmission',
    it: 'Velocità di trasmissione',
    es: 'Velocidad de transmisión',
    pl: 'Szybkość transmisji',
    uk: 'Швидкість передачі',
    'zh-cn': '排放速度',
  },
  'Network host': {
    en: 'Network host',
    de: 'Netzwerkhost',
    ru: 'Сеть host',
    pt: 'Host de rede',
    nl: 'Netwerk gast',
    fr: 'Network host',
    it: 'Host di rete',
    es: 'Network host',
    pl: 'Hosta sieci',
    uk: 'Мережевий хост',
    'zh-cn': '网络托管',
  },
  'Network port': {
    en: 'Network port',
    de: 'Netzwerkport',
    ru: 'Сетевой порт',
    pt: 'Porta de rede',
    nl: 'Netwerk',
    fr: 'Network port',
    it: 'Porta di rete',
    es: 'Puerto de red',
    pl: 'Port',
    uk: 'Мережевий порт',
    'zh-cn': '港口',
  },
  'Supports rfc2217': {
    en: 'Supports rfc2217',
    de: 'Unterstützt rfc2217',
    ru: 'Поддерживает rfc2217',
    pt: 'Suporta rfc2217',
    nl: 'Vertaling:',
    fr: 'Supports rfc2217',
    it: 'Supporta rfc2217',
    es: 'Supports rfc2217',
    pl: 'Wsparcie rfc2217',
    uk: 'Підтримує rfc2217',
    'zh-cn': 'B. 支助 rfc2217',
  },
  'Cycle time in minutes': {
    en: 'Cycle time in minutes',
    de: 'Zykluszeit in Minuten',
    ru: 'Время цикла в минутах',
    pt: 'Tempo de ciclo em minutos',
    nl: 'Cycle tijd in minuten',
    fr: 'Temps de cycle en minutes',
    it: 'Tempo di ciclo in minuti',
    es: 'Tiempo del ciclo en minutos',
    pl: 'Czas cykliczny w minutę',
    uk: 'Час циклу за хвилину',
    'zh-cn': '时间',
  },
  'Download the battery information data': {
    en: 'Download the battery information data',
    de: 'Laden Sie die Daten der Batterieinformationen herunter',
    ru: 'Скачайте данные по информации о аккумуляторе',
    pt: 'Baixar os dados da informação da bateria',
    nl: 'Download de accu informatie gegevens',
    fr: "Télécharger les données d'information sur la batterie",
    it: 'Scarica i dati delle informazioni sulla batteria',
    es: 'Descarga los datos de la información de la batería',
    pl: 'Download akumulator information data',
    uk: 'Завантажити дані про акумулятор',
    'zh-cn': '储存电池信息数据',
  },
  'Download the battery power data': {
    en: 'Download the battery power data',
    de: 'Batteriestromdaten herunterladen',
    ru: 'Загрузите данные по мощности батареи',
    pt: 'Baixar os dados de energia da bateria',
    nl: 'Download de accu power gegevens',
    fr: 'Télécharger les données de puissance de la batterie',
    it: 'Scarica i dati della batteria',
    es: 'Descarga los datos de energía de la batería',
    pl: 'Download the battery power data',
    uk: 'Завантажити дані живлення батареї',
    'zh-cn': 'D. 装有电池力数据',
  },
  'Download the battery statistics data': {
    en: 'Download the battery statistics data',
    de: 'Laden Sie die Daten der Batteriestatistik herunter',
    ru: 'Загрузить данные статистики батареи',
    pt: 'Baixar os dados de estatísticas da bateria',
    nl: 'Download de accu statistieken',
    fr: 'Télécharger les données statistiques de la batterie',
    it: 'Scarica i dati statistici della batteria',
    es: 'Descarga los datos de las estadísticas de batería',
    pl: 'Download the battery Statistics data',
    uk: 'Завантажити дані статистики батареї',
    'zh-cn': '储存电池统计数据',
  },
  'Download the battery cells data': {
    en: 'Download the battery cells data',
    de: 'Batteriezellendaten herunterladen',
    ru: 'Загрузите данные клеток батареи',
    pt: 'Baixe os dados das células da bateria',
    nl: 'Download de accu cellen data',
    fr: 'Télécharger les données des piles',
    it: 'Scarica i dati delle celle della batteria',
    es: 'Descargue los datos de las células de la batería',
    pl: 'Download the battery cells data',
    uk: 'Завантажити дані батарейок',
    'zh-cn': '电池组数据储存',
  },
  'Download the battery cells state of health': {
    en: 'Download the battery cells state of health',
    de: 'Laden Sie den Gesundheitszustand der Batteriezellen herunter',
    ru: 'Скачать состояние клеток батареи здоровья',
    pt: 'Baixar as células da bateria estado de saúde',
    nl: 'Download de batterij cellen staat van gezondheid',
    fr: "Télécharger l'état de santé des piles",
    it: 'Scarica lo stato delle celle della batteria',
    es: 'Descarga las células de la batería estado de salud',
    pl: 'Download the battery cells state of health',
    uk: "Завантажити стан клітин батареї для здоров'я",
    'zh-cn': 'D. 装有电池的健康状况',
  },
  'Download the log data': {
    en: 'Download the log data',
    de: 'Log-Daten herunterladen',
    ru: 'Скачать лог-данные',
    pt: 'Faça o download dos dados de log',
    nl: 'Download de loggegevens',
    fr: 'Télécharger les données du journal',
    it: 'Scarica i dati di registro',
    es: 'Descargar los datos de registro',
    pl: 'Download the log data',
    uk: 'Завантажити дані журналу',
    'zh-cn': 'D. 固体物数据',
  },
  'Download the time information': {
    en: 'Download the time information',
    de: 'Zeitinformationen herunterladen',
    ru: 'Скачать информацию о времени',
    pt: 'Baixe as informações do tempo',
    nl: 'Download de tijd informatie',
    fr: 'Télécharger les informations horaires',
    it: 'Scarica le informazioni sul tempo',
    es: 'Descargar la información del tiempo',
    pl: 'Download loaded time information',
    uk: 'Завантажити інформацію про час',
    'zh-cn': 'D. 掌握时间信息',
  },
};
